project:
  type: website

website:
  title: "Movement Visualizations"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: jekyll-theme-minimal
    toc: true

editor: visual

