project:
  type: website

website:
  title: "Movement Visualizations"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    remote_theme: pages-themes/minimal@v0.2.0

editor: visual

